# Generated by Django 6.0.7 on 2026-07-21 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kam', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='prospectdossier',
            name='billing_address',
            field=models.TextField(blank=True, default='', help_text='Adresse complète de facturation'),
        ),
        migrations.AddField(
            model_name='prospectdossier',
            name='contact_name',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='prospectdossier',
            name='is_complete',
            field=models.BooleanField(default=False, help_text='Indique si le dossier contractuel est complet'),
        ),
        migrations.AddField(
            model_name='prospectdossier',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='prospectdossier',
            name='rccm',
            field=models.CharField(blank=True, default='', help_text="Numéro d'immatriculation RCCM", max_length=100),
        ),
    ]
