# Generated by Django 5.2.14 on 2026-08-19 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kam', '0006_fix_legacy_null_constraints'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prospectdossier',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
