# Generated by Django 5.2.14 on 2026-09-21 15:47

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kam', '0009_kamvisitreport_crm_payload_and_more'),
        ('sales', '0018_accountprojection_sourceobservation_evidence_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RelationshipCoverage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('contact_name', models.CharField(help_text="Nom complet de l'interlocuteur", max_length=150)),
                ('contact_role', models.CharField(help_text="Titre officiel dans l'entreprise (ex: DAF, DSI)", max_length=100)),
                ('contact_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('contact_phone', models.CharField(blank=True, default='', max_length=50)),
                ('role_classification', models.CharField(choices=[('ECONOMIC_BUYER', 'Acheteur Économique (DG, DAF, Propriétaire)'), ('TECH_DECIDER', 'Décideur Technique (DSI, Responsable IT)'), ('CHAMPION', 'Champion Interne (Sponsor pro-MSP)'), ('DETRACTOR', 'Détracteur / Bloqueur (Soutien concurrent)'), ('END_USER', 'Utilisateur Final / Métier'), ('GATEKEEPER', "Contrôleur d'accès / Secrétaire général")], db_index=True, default='CHAMPION', max_length=30)),
                ('influence_level', models.CharField(choices=[('HIGH', 'Influence Majeure / Décisionnaire direct'), ('MEDIUM', 'Influence Forte / Prescripteur'), ('LOW', 'Influence Faible / Consultatif')], default='MEDIUM', max_length=10)),
                ('coverage_status', models.CharField(choices=[('COVERED', 'Couvert (Relation active prouvée < 60j)'), ('SINGLE_POINT_OF_FAILURE', 'Point Unique de Défaillance (Mono-champion)'), ('MISSING', 'Identifié mais non rencontré / Non couvert'), ('UNKNOWN', "Rôle non identifié dans l'entreprise")], db_index=True, default='MISSING', max_length=30)),
                ('is_mono_champion_risk', models.BooleanField(db_index=True, default=False, help_text="Vrai si l'opportunité dépend exclusivement de ce seul contact")),
                ('last_interaction_at', models.DateTimeField(blank=True, help_text='Date de la dernière interaction prouvée', null=True)),
                ('notes', models.TextField(blank=True, default='', help_text='Notes de posture, attentes et motivations')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('enterprise', models.ForeignKey(help_text='Entreprise (PME ou Grand Compte) pilotée par le KAM', on_delete=django.db.models.deletion.CASCADE, related_name='relationship_coverages', to='sales.enterprise')),
                ('last_interaction_proof', models.ForeignKey(blank=True, help_text='Preuve formelle de la dernière interaction', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contact_interactions', to='sales.evidence')),
            ],
            options={
                'verbose_name': 'Couverture Relationnelle',
                'verbose_name_plural': 'Couvertures Relationnelles',
                'ordering': ['enterprise', '-influence_level', 'contact_name'],
            },
        ),
    ]
