# Generated by Django 5.2.14 on 2026-09-21 16:17

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kam', '0010_relationshipcoverage'),
    ]

    operations = [
        migrations.CreateModel(
            name='SyncOperation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('target_system', models.CharField(choices=[('DYNAMICS_365', 'Microsoft Dynamics 365 Dataverse'), ('KAABU', 'CRM Kaabu Orange')], db_index=True, default='DYNAMICS_365', max_length=30)),
                ('entity_type', models.CharField(choices=[('ACCOUNT', 'Compte Entreprise (account)'), ('APPOINTMENT', 'Rendez-vous / Compte-rendu (appointment)'), ('CONTACT', 'Contact / Partie prenante (contact)'), ('OPPORTUNITY', 'Opportunité B2B (opportunity)')], db_index=True, max_length=30)),
                ('entity_id', models.CharField(db_index=True, help_text="ID interne de l'entité Onbora", max_length=100)),
                ('operation', models.CharField(choices=[('CREATE', 'Création'), ('UPDATE', 'Mise à jour'), ('UPSERT', 'Création ou Mise à jour')], default='UPSERT', max_length=20)),
                ('payload', models.JSONField(default=dict, help_text="Schéma formaté pour l'API Dataverse OData v9.2")),
                ('status', models.CharField(choices=[('PENDING', 'En attente de traitement par le worker'), ('PROCESSING', "En cours d'exécution"), ('SUCCEEDED', 'Synchronisé avec succès dans Dynamics'), ('FAILED', 'Échec définitif après réessais'), ('CONFLICT', 'Conflit de version OData nécessitant arbitrage')], db_index=True, default='PENDING', max_length=20)),
                ('retry_count', models.IntegerField(default=0)),
                ('max_retries', models.IntegerField(default=5)),
                ('last_error', models.TextField(blank=True, default='')),
                ('remote_id', models.CharField(blank=True, default='', help_text='GUID distant Dataverse retourné', max_length=150)),
                ('scheduled_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Opération de Synchronisation Outbox',
                'verbose_name_plural': 'Opérations de Synchronisation Outbox',
                'ordering': ['scheduled_at'],
            },
        ),
    ]
