# Generated by Django 5.2.14 on 2026-09-21 16:23

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kam', '0011_syncoperation'),
        ('sales', '0019_idempotencyrecord'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountMemoryEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('DECISION', 'Décision Stratégique Validée'), ('PROMISE', 'Promesse Commerciale / Engagement FAI'), ('INCIDENT', 'Incident Majeur / Litige SLA'), ('MILESTONE', 'Jalon Contractuel / Avenant'), ('ORGANIZATION_CHANGE', "Changement dans l'Organigramme Client")], db_index=True, max_length=30)),
                ('summary', models.CharField(help_text="Titre concis de l'événement", max_length=255)),
                ('details', models.TextField(help_text='Description factuelle, engagements et contexte')),
                ('occurred_at', models.DateTimeField(db_index=True, help_text="Date réelle à laquelle l'événement s'est produit")),
                ('is_critical', models.BooleanField(db_index=True, default=False, help_text="Drapeau d'attention prioritaire lors de la passation de compte")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, help_text="KAM ou manager ayant consigné l'événement", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logged_account_events', to=settings.AUTH_USER_MODEL)),
                ('enterprise', models.ForeignKey(help_text="Compte concerné par l'événement de mémoire", on_delete=django.db.models.deletion.CASCADE, related_name='memory_events', to='sales.enterprise')),
                ('evidence', models.ForeignKey(blank=True, help_text='Preuve formelle associée (rapport, email, observation)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='memory_events', to='sales.evidence')),
            ],
            options={
                'verbose_name': 'Événement Mémoire de Compte',
                'verbose_name_plural': 'Événements Mémoire de Compte',
                'ordering': ['-occurred_at', '-created_at'],
            },
        ),
    ]
