# Generated by Django 5.2.14 on 2026-09-22 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kam', '0014_backfill_kamappointment_visit_purpose'),
    ]

    operations = [
        migrations.AddField(
            model_name='precallbriefing',
            name='analysis_data',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
