# Generated by Django 5.2.14 on 2026-09-29 15:37

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kam', '0015_precallbriefing_analysis_data'),
        ('sales', '0019_idempotencyrecord'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChurnRadarAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('health_score', models.IntegerField(default=100, help_text='Score de santé déterministe de 0 à 100 (>=70: Sain, 40-69: Surveillance, <40: Risque élevé)')),
                ('churn_risk_score', models.IntegerField(default=0, help_text='Risque de churn (100 - health_score)')),
                ('risk_level', models.CharField(choices=[('LOW', 'Sain'), ('MEDIUM', 'Sous surveillance'), ('HIGH', 'À risque élevé'), ('CRITICAL', 'Critique')], db_index=True, default='LOW', max_length=20)),
                ('priority_level', models.CharField(choices=[('P1', 'Priorité 1 - Immédiate'), ('P2', 'Priorité 2 - Sous 48h'), ('P3', 'Priorité 3 - Suivi normal')], default='P3', max_length=10)),
                ('trend', models.CharField(choices=[('UP', 'En amélioration'), ('DOWN', 'En dégradation'), ('STABLE', 'Stable')], default='STABLE', max_length=10)),
                ('risk_reasons', models.JSONField(blank=True, default=list, help_text='Liste des signaux factuels motivant le score')),
                ('retention_plan', models.JSONField(blank=True, default=dict, help_text="Plan d'action de rétention (urgence, action concrète, email de conciliation)")),
                ('upsell_opportunities', models.JSONField(blank=True, default=list, help_text="Opportunités d'expansion identifiées sur le catalogue Orange Business B2B")),
                ('days_without_action', models.IntegerField(default=0, help_text='Jours écoulés sans interaction KAM ni RDV')),
                ('is_renewal_imminent', models.BooleanField(db_index=True, default=False, help_text='True si le contrat arrive à échéance dans <= 90 jours')),
                ('renewal_days', models.IntegerField(blank=True, help_text="Jours restants avant l'échéance contractuelle", null=True)),
                ('last_action_at', models.DateTimeField(blank=True, help_text='Date de la dernière interaction prouvée', null=True)),
                ('next_action_at', models.DateTimeField(blank=True, help_text='Date du prochain rendez-vous planifié', null=True)),
                ('ai_scored_at', models.DateTimeField(blank=True, help_text='Horodatage de la dernière analyse par Core AI', null=True)),
                ('rules_version', models.CharField(default='v1.0', help_text='Version des règles métier appliquées', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('enterprise', models.OneToOneField(help_text='Entreprise auditée par le Radar de Churn', on_delete=django.db.models.deletion.CASCADE, related_name='churn_assessment', to='sales.enterprise')),
            ],
            options={
                'verbose_name': 'Évaluation Radar Churn',
                'verbose_name_plural': 'Évaluations Radar Churn',
                'ordering': ['health_score', '-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ChurnRadarSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('health_score', models.IntegerField()),
                ('churn_risk_score', models.IntegerField()),
                ('risk_level', models.CharField(max_length=20)),
                ('calculated_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('enterprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='churn_snapshots', to='sales.enterprise')),
            ],
            options={
                'verbose_name': 'Instantané Radar Churn',
                'verbose_name_plural': 'Instantanés Radar Churn',
                'ordering': ['-calculated_at'],
            },
        ),
    ]
