# Generated by Django 6.0.7 on 2026-07-21 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_available',
            field=models.BooleanField(default=True, help_text='Disponibilité immédiate pour affectation'),
        ),
        migrations.AddField(
            model_name='user',
            name='location',
            field=models.CharField(blank=True, help_text="Ville / Région d'affectation", max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('CLIENT_B2B', 'Client B2B'), ('SALESPERSON', 'Prospecteur / Commercial'), ('KAM', 'Key Account Manager'), ('ADMIN', 'Administrateur MSP')], default='CLIENT_B2B', max_length=20),
        ),
    ]
