# Generated by Django 5.2.14 on 2026-08-21 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('CLIENT_B2B', 'Client B2B'), ('SALESPERSON', 'Prospecteur / Commercial'), ('KAM', 'Key Account Manager'), ('SUPERVISOR', 'Superviseur / Gestionnaire Back-office'), ('ADMIN', 'Administrateur MSP')], default='CLIENT_B2B', max_length=20),
        ),
    ]
