# Generated by Django 5.2.14 on 2026-09-04 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='kam_specialization',
            field=models.CharField(blank=True, choices=[('GRAND_COMPTE', 'Grands Comptes (> 1M$)'), ('PME', 'PME (100k$ - 1M$)')], default='GRAND_COMPTE', help_text='Segmentation du KAM dans le KAM Office', max_length=20, null=True),
        ),
    ]
