# Generated by Django 5.2.14 on 2026-09-07 18:01

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_user_avatar'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIAssistantConversation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(default='Nouvelle session', max_length=255)),
                ('is_pinned', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='AIAssistantMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('user', 'Utilisateur'), ('assistant', 'Copilote IA'), ('system', 'Système')], max_length=20)),
                ('content', models.TextField(help_text='Texte du message ou de la réponse')),
                ('action_type', models.CharField(blank=True, help_text="Type d'action métier détectée ou exécutée", max_length=60, null=True)),
                ('action_payload', models.JSONField(blank=True, default=dict, help_text="Données d'entrée ou paramètres de l'action")),
                ('action_result', models.JSONField(blank=True, default=dict, help_text="Résultat structuré retourné par l'action")),
                ('action_status', models.CharField(choices=[('NONE', 'Aucune action'), ('PROPOSED', 'Action proposée'), ('EXECUTED', 'Action exécutée'), ('FAILED', 'Échec action')], default='NONE', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='accounts.aiassistantconversation')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserAIAssistant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(default='Copilote Onbora B2B', help_text="Nom personnalisé donné à l'assistant par l'utilisateur", max_length=100)),
                ('role_scope', models.CharField(default='KAM', help_text='Périmètre de rôle autorisé', max_length=30)),
                ('allowed_actions', models.JSONField(blank=True, default=list, help_text='Actions automatisables autorisées selon le rôle')),
                ('system_prompt', models.TextField(blank=True, default='', help_text='Contexte métier et règles de fonctionnement du copilote')),
                ('custom_context', models.JSONField(blank=True, default=dict, help_text='Mémoire contextuelle et préférences persistantes')),
                ('avatar', models.CharField(blank=True, default='bot', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai_assistant', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='aiassistantconversation',
            name='assistant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='accounts.useraiassistant'),
        ),
    ]
