# Generated by Django 5.2.14 on 2026-08-19 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0005_alter_demoevent_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demoevent',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
