# Generated by Django 6.0.7 on 2026-07-18 20:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientConversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('ARCHIVED', 'Archivée'), ('TRANSMITTED', 'Transmise au KAM')], default='ACTIVE', max_length=20)),
                ('channel', models.CharField(choices=[('PORTAL', 'Portail MSP'), ('WIDGET', 'Widget Externe'), ('MAXIT', 'Mini-App Maxit')], default='PORTAL', max_length=20)),
                ('extracted_profile', models.JSONField(blank=True, default=dict, help_text='Profil dynamique extrait des besoins (secteur, taille, problèmes, outils, etc.)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ClientConversationMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(choices=[('USER', 'Utilisateur'), ('AI', 'Intelligence Artificielle')], max_length=10)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='discovery.clientconversation')),
            ],
        ),
    ]
