# Generated by Django 5.2.14 on 2026-09-21 16:05

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discovery', '0003_alter_clientconversation_id_and_more'),
        ('sales', '0018_accountprojection_sourceobservation_evidence_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QualificationRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('initial_segment', models.CharField(choices=[('SOHO', 'SOHO / TPE'), ('PME', 'PME (Petites et Moyennes Entreprises)'), ('KAM', 'Grand Compte / Compte Stratégique')], default='SOHO', help_text='Segment attribué avant la qualification', max_length=20)),
                ('effective_segment', models.CharField(choices=[('SOHO', 'SOHO / TPE'), ('PME', 'PME (Petites et Moyennes Entreprises)'), ('KAM', 'Grand Compte / Compte Stratégique')], default='SOHO', help_text='Segment résultant après évaluation des règles métier', max_length=20)),
                ('pivot_triggered', models.BooleanField(db_index=True, default=False, help_text='Vrai si un dépassement de seuil a déclenché un pivot vers un segment supérieur')),
                ('pivot_reason', models.TextField(blank=True, default='', help_text='Explication factuelle et déterministe de la bascule')),
                ('completeness_score', models.DecimalField(decimal_places=2, default=0.0, help_text='Score de complétude (0.00 à 1.00)', max_digits=4)),
                ('answers', models.JSONField(blank=True, default=dict, help_text='Ensemble structuré des réponses aux questions de découverte')),
                ('status', models.CharField(choices=[('IN_PROGRESS', 'En cours de qualification'), ('COMPLETED', 'Qualification complétée'), ('PIVOTED', 'Requalifiée / Bascule de segment effectuée')], db_index=True, default='COMPLETED', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('conducted_by', models.ForeignKey(blank=True, help_text='Agent ayant mené la découverte (Commercial SOHO ou KAM)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conducted_qualifications', to=settings.AUTH_USER_MODEL)),
                ('enterprise', models.ForeignKey(help_text='Entreprise qualifiée', on_delete=django.db.models.deletion.CASCADE, related_name='qualifications', to='sales.enterprise')),
            ],
            options={
                'verbose_name': 'Session de Qualification',
                'verbose_name_plural': 'Sessions de Qualification',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HandoffDossier',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('from_role', models.CharField(choices=[('SOHO_REPRESENTATIVE', 'Prospecteur / Prestataire Terrain SOHO'), ('OUTGOING_KAM', 'KAM Sortant (Passation interne)'), ('FIELD_PROSPECTOR', 'Commercial Terrain')], default='SOHO_REPRESENTATIVE', max_length=30)),
                ('target_segment', models.CharField(choices=[('PME', 'PME (Petites et Moyennes Entreprises)'), ('KAM', 'Grand Compte / Compte Stratégique')], default='PME', max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'En attente de prise en charge KAM'), ('ACCEPTED', 'Accepté & Intégré au portefeuille KAM'), ('RETURNED', 'Renvoyé au prospecteur (Non éligible PME)')], db_index=True, default='PENDING', max_length=20)),
                ('transfer_notes', models.TextField(blank=True, default='', help_text='Synthèse des constats terrain et justification du potentiel PME')),
                ('return_reason', models.TextField(blank=True, default='', help_text='Motif explicatif en cas de retour au prospecteur')),
                ('transferred_at', models.DateTimeField(auto_now_add=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='decided_handoffs', to=settings.AUTH_USER_MODEL)),
                ('enterprise', models.ForeignKey(help_text='Compte requalifié nécessitant prise en charge', on_delete=django.db.models.deletion.CASCADE, related_name='handoff_dossiers', to='sales.enterprise')),
                ('from_user', models.ForeignKey(help_text='Agent émetteur de la passation (Prospecteur SOHO)', on_delete=django.db.models.deletion.CASCADE, related_name='sent_handoffs', to=settings.AUTH_USER_MODEL)),
                ('to_kam', models.ForeignKey(blank=True, help_text='KAM assigné à la prise en charge', limit_choices_to={'role': 'KAM'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_handoffs', to=settings.AUTH_USER_MODEL)),
                ('qualification', models.ForeignKey(blank=True, help_text="Session de qualification à l'origine du pivot", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='handoff_dossiers', to='discovery.qualificationrecord')),
            ],
            options={
                'verbose_name': 'Dossier de Handoff (Bascule)',
                'verbose_name_plural': 'Dossiers de Handoff (Bascules)',
                'ordering': ['-transferred_at'],
            },
        ),
    ]
