/// Memoji Avatar Model & Organized Catalog
/// Structure : Hommes / Femmes, ordonnés du plus âgé au plus jeune,
/// avec alternance équilibrée des origines (Blanc, Noir, Arabe, Asiatique).
class MemojiItem {
  final int id;
  final String assetPath;
  final String gender; // 'homme' | 'femme'
  final String ethnicity; // 'blanc' | 'noir' | 'arabe' | 'asiatique'
  final String ageTier; // 'senior' | 'adulte' | 'jeune'

  const MemojiItem({
    required this.id,
    required this.assetPath,
    required this.gender,
    required this.ethnicity,
    required this.ageTier,
  });
}

class MemojiData {
  /// Memojis Hommes ordonnés (Séniors -> Adultes -> Jeunes) & Origines mélangées
  static const List<MemojiItem> men = [
    MemojiItem(
      id: 56,
      assetPath: 'assets/memojis/memoji_056.png',
      gender: 'homme',
      ethnicity: 'noir',
      ageTier: 'senior',
    ),
    MemojiItem(
      id: 19,
      assetPath: 'assets/memojis/memoji_019.png',
      gender: 'homme',
      ethnicity: 'arabe',
      ageTier: 'senior',
    ),
    MemojiItem(
      id: 80,
      assetPath: 'assets/memojis/memoji_080.png',
      gender: 'homme',
      ethnicity: 'asiatique',
      ageTier: 'senior',
    ),
    MemojiItem(
      id: 62,
      assetPath: 'assets/memojis/memoji_062.png',
      gender: 'homme',
      ethnicity: 'noir',
      ageTier: 'senior',
    ),
    MemojiItem(
      id: 31,
      assetPath: 'assets/memojis/memoji_031.png',
      gender: 'homme',
      ethnicity: 'blanc',
      ageTier: 'adulte',
    ),
    MemojiItem(
      id: 3,
      assetPath: 'assets/memojis/memoji_003.png',
      gender: 'homme',
      ethnicity: 'noir',
      ageTier: 'adulte',
    ),
    MemojiItem(
      id: 21,
      assetPath: 'assets/memojis/memoji_021.png',
      gender: 'homme',
      ethnicity: 'arabe',
      ageTier: 'adulte',
    ),
    MemojiItem(
      id: 84,
      assetPath: 'assets/memojis/memoji_084.png',
      gender: 'homme',
      ethnicity: 'asiatique',
      ageTier: 'adulte',
    ),
    MemojiItem(
      id: 38,
      assetPath: 'assets/memojis/memoji_038.png',
      gender: 'homme',
      ethnicity: 'blanc',
      ageTier: 'adulte',
    ),
    MemojiItem(
      id: 7,
      assetPath: 'assets/memojis/memoji_007.png',
      gender: 'homme',
      ethnicity: 'noir',
      ageTier: 'adulte',
    ),
    MemojiItem(
      id: 23,
      assetPath: 'assets/memojis/memoji_023.png',
      gender: 'homme',
      ethnicity: 'arabe',
      ageTier: 'adulte',
    ),
    MemojiItem(
      id: 41,
      assetPath: 'assets/memojis/memoji_041.png',
      gender: 'homme',
      ethnicity: 'blanc',
      ageTier: 'adulte',
    ),
    MemojiItem(
      id: 27,
      assetPath: 'assets/memojis/memoji_027.png',
      gender: 'homme',
      ethnicity: 'noir',
      ageTier: 'adulte',
    ),
    MemojiItem(
      id: 26,
      assetPath: 'assets/memojis/memoji_026.png',
      gender: 'homme',
      ethnicity: 'arabe',
      ageTier: 'adulte',
    ),
    MemojiItem(
      id: 46,
      assetPath: 'assets/memojis/memoji_046.png',
      gender: 'homme',
      ethnicity: 'blanc',
      ageTier: 'adulte',
    ),
    MemojiItem(
      id: 58,
      assetPath: 'assets/memojis/memoji_058.png',
      gender: 'homme',
      ethnicity: 'noir',
      ageTier: 'adulte',
    ),
    MemojiItem(
      id: 60,
      assetPath: 'assets/memojis/memoji_060.png',
      gender: 'homme',
      ethnicity: 'noir',
      ageTier: 'adulte',
    ),
    MemojiItem(
      id: 69,
      assetPath: 'assets/memojis/memoji_069.png',
      gender: 'homme',
      ethnicity: 'noir',
      ageTier: 'adulte',
    ),
    MemojiItem(
      id: 36,
      assetPath: 'assets/memojis/memoji_036.png',
      gender: 'homme',
      ethnicity: 'blanc',
      ageTier: 'jeune',
    ),
    MemojiItem(
      id: 1,
      assetPath: 'assets/memojis/memoji_001.png',
      gender: 'homme',
      ethnicity: 'noir',
      ageTier: 'jeune',
    ),
    MemojiItem(
      id: 20,
      assetPath: 'assets/memojis/memoji_020.png',
      gender: 'homme',
      ethnicity: 'arabe',
      ageTier: 'jeune',
    ),
    MemojiItem(
      id: 82,
      assetPath: 'assets/memojis/memoji_082.png',
      gender: 'homme',
      ethnicity: 'asiatique',
      ageTier: 'jeune',
    ),
    MemojiItem(
      id: 39,
      assetPath: 'assets/memojis/memoji_039.png',
      gender: 'homme',
      ethnicity: 'blanc',
      ageTier: 'jeune',
    ),
    MemojiItem(
      id: 2,
      assetPath: 'assets/memojis/memoji_002.png',
      gender: 'homme',
      ethnicity: 'noir',
      ageTier: 'jeune',
    ),
    MemojiItem(
      id: 22,
      assetPath: 'assets/memojis/memoji_022.png',
      gender: 'homme',
      ethnicity: 'arabe',
      ageTier: 'jeune',
    ),
    MemojiItem(
      id: 86,
      assetPath: 'assets/memojis/memoji_086.png',
      gender: 'homme',
      ethnicity: 'asiatique',
      ageTier: 'jeune',
    ),
    MemojiItem(
      id: 50,
      assetPath: 'assets/memojis/memoji_050.png',
      gender: 'homme',
      ethnicity: 'blanc',
      ageTier: 'jeune',
    ),
    MemojiItem(
      id: 4,
      assetPath: 'assets/memojis/memoji_004.png',
      gender: 'homme',
      ethnicity: 'noir',
      ageTier: 'jeune',
    ),
    MemojiItem(
      id: 92,
      assetPath: 'assets/memojis/memoji_092.png',
      gender: 'homme',
      ethnicity: 'asiatique',
      ageTier: 'jeune',
    ),
    MemojiItem(
      id: 52,
      assetPath: 'assets/memojis/memoji_052.png',
      gender: 'homme',
      ethnicity: 'blanc',
      ageTier: 'jeune',
    ),
    MemojiItem(
      id: 5,
      assetPath: 'assets/memojis/memoji_005.png',
      gender: 'homme',
      ethnicity: 'noir',
      ageTier: 'jeune',
    ),
    MemojiItem(
      id: 93,
      assetPath: 'assets/memojis/memoji_093.png',
      gender: 'homme',
      ethnicity: 'asiatique',
      ageTier: 'jeune',
    ),
    MemojiItem(
      id: 54,
      assetPath: 'assets/memojis/memoji_054.png',
      gender: 'homme',
      ethnicity: 'blanc',
      ageTier: 'jeune',
    ),
    MemojiItem(
      id: 15,
      assetPath: 'assets/memojis/memoji_015.png',
      gender: 'homme',
      ethnicity: 'noir',
      ageTier: 'jeune',
    ),
    MemojiItem(
      id: 97,
      assetPath: 'assets/memojis/memoji_097.png',
      gender: 'homme',
      ethnicity: 'asiatique',
      ageTier: 'jeune',
    ),
    MemojiItem(
      id: 17,
      assetPath: 'assets/memojis/memoji_017.png',
      gender: 'homme',
      ethnicity: 'noir',
      ageTier: 'jeune',
    ),
    MemojiItem(
      id: 99,
      assetPath: 'assets/memojis/memoji_099.png',
      gender: 'homme',
      ethnicity: 'asiatique',
      ageTier: 'jeune',
    ),
    MemojiItem(
      id: 33,
      assetPath: 'assets/memojis/memoji_033.png',
      gender: 'homme',
      ethnicity: 'noir',
      ageTier: 'jeune',
    ),
    MemojiItem(
      id: 101,
      assetPath: 'assets/memojis/memoji_101.png',
      gender: 'homme',
      ethnicity: 'asiatique',
      ageTier: 'jeune',
    ),
    MemojiItem(
      id: 61,
      assetPath: 'assets/memojis/memoji_061.png',
      gender: 'homme',
      ethnicity: 'noir',
      ageTier: 'jeune',
    ),
    MemojiItem(
      id: 64,
      assetPath: 'assets/memojis/memoji_064.png',
      gender: 'homme',
      ethnicity: 'noir',
      ageTier: 'jeune',
    ),
    MemojiItem(
      id: 70,
      assetPath: 'assets/memojis/memoji_070.png',
      gender: 'homme',
      ethnicity: 'noir',
      ageTier: 'jeune',
    ),
    MemojiItem(
      id: 74,
      assetPath: 'assets/memojis/memoji_074.png',
      gender: 'homme',
      ethnicity: 'noir',
      ageTier: 'jeune',
    ),
    MemojiItem(
      id: 76,
      assetPath: 'assets/memojis/memoji_076.png',
      gender: 'homme',
      ethnicity: 'noir',
      ageTier: 'jeune',
    ),
    MemojiItem(
      id: 78,
      assetPath: 'assets/memojis/memoji_078.png',
      gender: 'homme',
      ethnicity: 'noir',
      ageTier: 'jeune',
    ),
  ];

  /// Memojis Femmes ordonnés (Séniors -> Adultes -> Jeunes) & Origines mélangées
  static const List<MemojiItem> women = [
    MemojiItem(
      id: 8,
      assetPath: 'assets/memojis/memoji_008.png',
      gender: 'femme',
      ethnicity: 'blanc',
      ageTier: 'senior',
    ),
    MemojiItem(
      id: 65,
      assetPath: 'assets/memojis/memoji_065.png',
      gender: 'femme',
      ethnicity: 'noir',
      ageTier: 'senior',
    ),
    MemojiItem(
      id: 87,
      assetPath: 'assets/memojis/memoji_087.png',
      gender: 'femme',
      ethnicity: 'asiatique',
      ageTier: 'senior',
    ),
    MemojiItem(
      id: 42,
      assetPath: 'assets/memojis/memoji_042.png',
      gender: 'femme',
      ethnicity: 'blanc',
      ageTier: 'senior',
    ),
    MemojiItem(
      id: 88,
      assetPath: 'assets/memojis/memoji_088.png',
      gender: 'femme',
      ethnicity: 'asiatique',
      ageTier: 'senior',
    ),
    MemojiItem(
      id: 85,
      assetPath: 'assets/memojis/memoji_085.png',
      gender: 'femme',
      ethnicity: 'asiatique',
      ageTier: 'adulte',
    ),
    MemojiItem(
      id: 95,
      assetPath: 'assets/memojis/memoji_095.png',
      gender: 'femme',
      ethnicity: 'asiatique',
      ageTier: 'adulte',
    ),
    MemojiItem(
      id: 25,
      assetPath: 'assets/memojis/memoji_025.png',
      gender: 'femme',
      ethnicity: 'blanc',
      ageTier: 'jeune',
    ),
    MemojiItem(
      id: 6,
      assetPath: 'assets/memojis/memoji_006.png',
      gender: 'femme',
      ethnicity: 'noir',
      ageTier: 'jeune',
    ),
    MemojiItem(
      id: 28,
      assetPath: 'assets/memojis/memoji_028.png',
      gender: 'femme',
      ethnicity: 'arabe',
      ageTier: 'jeune',
    ),
    MemojiItem(
      id: 81,
      assetPath: 'assets/memojis/memoji_081.png',
      gender: 'femme',
      ethnicity: 'asiatique',
      ageTier: 'jeune',
    ),
    MemojiItem(
      id: 35,
      assetPath: 'assets/memojis/memoji_035.png',
      gender: 'femme',
      ethnicity: 'blanc',
      ageTier: 'jeune',
    ),
    MemojiItem(
      id: 9,
      assetPath: 'assets/memojis/memoji_009.png',
      gender: 'femme',
      ethnicity: 'noir',
      ageTier: 'jeune',
    ),
    MemojiItem(
      id: 30,
      assetPath: 'assets/memojis/memoji_030.png',
      gender: 'femme',
      ethnicity: 'arabe',
      ageTier: 'jeune',
    ),
    MemojiItem(
      id: 83,
      assetPath: 'assets/memojis/memoji_083.png',
      gender: 'femme',
      ethnicity: 'asiatique',
      ageTier: 'jeune',
    ),
    MemojiItem(
      id: 37,
      assetPath: 'assets/memojis/memoji_037.png',
      gender: 'femme',
      ethnicity: 'blanc',
      ageTier: 'jeune',
    ),
    MemojiItem(
      id: 10,
      assetPath: 'assets/memojis/memoji_010.png',
      gender: 'femme',
      ethnicity: 'noir',
      ageTier: 'jeune',
    ),
    MemojiItem(
      id: 32,
      assetPath: 'assets/memojis/memoji_032.png',
      gender: 'femme',
      ethnicity: 'arabe',
      ageTier: 'jeune',
    ),
    MemojiItem(
      id: 89,
      assetPath: 'assets/memojis/memoji_089.png',
      gender: 'femme',
      ethnicity: 'asiatique',
      ageTier: 'jeune',
    ),
    MemojiItem(
      id: 40,
      assetPath: 'assets/memojis/memoji_040.png',
      gender: 'femme',
      ethnicity: 'blanc',
      ageTier: 'jeune',
    ),
    MemojiItem(
      id: 11,
      assetPath: 'assets/memojis/memoji_011.png',
      gender: 'femme',
      ethnicity: 'noir',
      ageTier: 'jeune',
    ),
    MemojiItem(
      id: 34,
      assetPath: 'assets/memojis/memoji_034.png',
      gender: 'femme',
      ethnicity: 'arabe',
      ageTier: 'jeune',
    ),
    MemojiItem(
      id: 91,
      assetPath: 'assets/memojis/memoji_091.png',
      gender: 'femme',
      ethnicity: 'asiatique',
      ageTier: 'jeune',
    ),
    MemojiItem(
      id: 43,
      assetPath: 'assets/memojis/memoji_043.png',
      gender: 'femme',
      ethnicity: 'blanc',
      ageTier: 'jeune',
    ),
    MemojiItem(
      id: 12,
      assetPath: 'assets/memojis/memoji_012.png',
      gender: 'femme',
      ethnicity: 'noir',
      ageTier: 'jeune',
    ),
    MemojiItem(
      id: 55,
      assetPath: 'assets/memojis/memoji_055.png',
      gender: 'femme',
      ethnicity: 'arabe',
      ageTier: 'jeune',
    ),
    MemojiItem(
      id: 94,
      assetPath: 'assets/memojis/memoji_094.png',
      gender: 'femme',
      ethnicity: 'asiatique',
      ageTier: 'jeune',
    ),
    MemojiItem(
      id: 44,
      assetPath: 'assets/memojis/memoji_044.png',
      gender: 'femme',
      ethnicity: 'blanc',
      ageTier: 'jeune',
    ),
    MemojiItem(
      id: 13,
      assetPath: 'assets/memojis/memoji_013.png',
      gender: 'femme',
      ethnicity: 'noir',
      ageTier: 'jeune',
    ),
    MemojiItem(
      id: 96,
      assetPath: 'assets/memojis/memoji_096.png',
      gender: 'femme',
      ethnicity: 'asiatique',
      ageTier: 'jeune',
    ),
    MemojiItem(
      id: 45,
      assetPath: 'assets/memojis/memoji_045.png',
      gender: 'femme',
      ethnicity: 'blanc',
      ageTier: 'jeune',
    ),
    MemojiItem(
      id: 14,
      assetPath: 'assets/memojis/memoji_014.png',
      gender: 'femme',
      ethnicity: 'noir',
      ageTier: 'jeune',
    ),
    MemojiItem(
      id: 98,
      assetPath: 'assets/memojis/memoji_098.png',
      gender: 'femme',
      ethnicity: 'asiatique',
      ageTier: 'jeune',
    ),
    MemojiItem(
      id: 47,
      assetPath: 'assets/memojis/memoji_047.png',
      gender: 'femme',
      ethnicity: 'blanc',
      ageTier: 'jeune',
    ),
    MemojiItem(
      id: 16,
      assetPath: 'assets/memojis/memoji_016.png',
      gender: 'femme',
      ethnicity: 'noir',
      ageTier: 'jeune',
    ),
    MemojiItem(
      id: 100,
      assetPath: 'assets/memojis/memoji_100.png',
      gender: 'femme',
      ethnicity: 'asiatique',
      ageTier: 'jeune',
    ),
    MemojiItem(
      id: 48,
      assetPath: 'assets/memojis/memoji_048.png',
      gender: 'femme',
      ethnicity: 'blanc',
      ageTier: 'jeune',
    ),
    MemojiItem(
      id: 18,
      assetPath: 'assets/memojis/memoji_018.png',
      gender: 'femme',
      ethnicity: 'noir',
      ageTier: 'jeune',
    ),
    MemojiItem(
      id: 102,
      assetPath: 'assets/memojis/memoji_102.png',
      gender: 'femme',
      ethnicity: 'asiatique',
      ageTier: 'jeune',
    ),
    MemojiItem(
      id: 49,
      assetPath: 'assets/memojis/memoji_049.png',
      gender: 'femme',
      ethnicity: 'blanc',
      ageTier: 'jeune',
    ),
    MemojiItem(
      id: 24,
      assetPath: 'assets/memojis/memoji_024.png',
      gender: 'femme',
      ethnicity: 'noir',
      ageTier: 'jeune',
    ),
    MemojiItem(
      id: 51,
      assetPath: 'assets/memojis/memoji_051.png',
      gender: 'femme',
      ethnicity: 'blanc',
      ageTier: 'jeune',
    ),
    MemojiItem(
      id: 29,
      assetPath: 'assets/memojis/memoji_029.png',
      gender: 'femme',
      ethnicity: 'noir',
      ageTier: 'jeune',
    ),
    MemojiItem(
      id: 53,
      assetPath: 'assets/memojis/memoji_053.png',
      gender: 'femme',
      ethnicity: 'blanc',
      ageTier: 'jeune',
    ),
    MemojiItem(
      id: 57,
      assetPath: 'assets/memojis/memoji_057.png',
      gender: 'femme',
      ethnicity: 'noir',
      ageTier: 'jeune',
    ),
    MemojiItem(
      id: 59,
      assetPath: 'assets/memojis/memoji_059.png',
      gender: 'femme',
      ethnicity: 'noir',
      ageTier: 'jeune',
    ),
    MemojiItem(
      id: 63,
      assetPath: 'assets/memojis/memoji_063.png',
      gender: 'femme',
      ethnicity: 'noir',
      ageTier: 'jeune',
    ),
    MemojiItem(
      id: 66,
      assetPath: 'assets/memojis/memoji_066.png',
      gender: 'femme',
      ethnicity: 'noir',
      ageTier: 'jeune',
    ),
    MemojiItem(
      id: 67,
      assetPath: 'assets/memojis/memoji_067.png',
      gender: 'femme',
      ethnicity: 'noir',
      ageTier: 'jeune',
    ),
    MemojiItem(
      id: 68,
      assetPath: 'assets/memojis/memoji_068.png',
      gender: 'femme',
      ethnicity: 'noir',
      ageTier: 'jeune',
    ),
    MemojiItem(
      id: 71,
      assetPath: 'assets/memojis/memoji_071.png',
      gender: 'femme',
      ethnicity: 'noir',
      ageTier: 'jeune',
    ),
    MemojiItem(
      id: 72,
      assetPath: 'assets/memojis/memoji_072.png',
      gender: 'femme',
      ethnicity: 'noir',
      ageTier: 'jeune',
    ),
    MemojiItem(
      id: 73,
      assetPath: 'assets/memojis/memoji_073.png',
      gender: 'femme',
      ethnicity: 'noir',
      ageTier: 'jeune',
    ),
    MemojiItem(
      id: 75,
      assetPath: 'assets/memojis/memoji_075.png',
      gender: 'femme',
      ethnicity: 'noir',
      ageTier: 'jeune',
    ),
    MemojiItem(
      id: 77,
      assetPath: 'assets/memojis/memoji_077.png',
      gender: 'femme',
      ethnicity: 'noir',
      ageTier: 'jeune',
    ),
    MemojiItem(
      id: 79,
      assetPath: 'assets/memojis/memoji_079.png',
      gender: 'femme',
      ethnicity: 'noir',
      ageTier: 'jeune',
    ),
    MemojiItem(
      id: 90,
      assetPath: 'assets/memojis/memoji_090.png',
      gender: 'femme',
      ethnicity: 'noir',
      ageTier: 'jeune',
    ),
  ];

  static List<MemojiItem> get all => [...men, ...women];

  static const String defaultMemoji = 'assets/memojis/memoji_001.png';
}
