# Generated by Django 5.2.14 on 2026-08-26 17:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_alter_servicecatalog_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfferQuestionnaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Titre du formulaire (ex: Questionnaire Qualification Fibre Pro)', max_length=200)),
                ('description', models.TextField(blank=True, default='', help_text='Description ou consignes pour le commercial')),
                ('target_offer_name', models.CharField(blank=True, default='', help_text="Nom de l'offre ciblée", max_length=150)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questionnaires', to='catalog.servicecatalog')),
            ],
        ),
        migrations.CreateModel(
            name='OfferQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(help_text='Libellé de la question', max_length=300)),
                ('question_type', models.CharField(choices=[('SINGLE_CHOICE', 'Choix Unique (Boutons Radio)'), ('MULTIPLE_CHOICE', 'Choix Multiples (Cases à cocher)'), ('BOOLEAN', 'Oui / Non'), ('TEXT', 'Texte Libre Court'), ('NUMBER', 'Nombre / Montant numérique')], default='SINGLE_CHOICE', max_length=30)),
                ('options', models.JSONField(blank=True, default=list, help_text="Liste des choix possibles (ex: ['1 à 5', '6 à 20', '20+'])")),
                ('is_required', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=1, help_text="Ordre d'affichage de la question")),
                ('help_text', models.CharField(blank=True, default='', help_text="Indication d'aide pour le commercial terrain", max_length=255)),
                ('scoring_weight', models.PositiveIntegerField(default=10, help_text='Poids de la question dans le calcul du score de qualification')),
                ('questionnaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='catalog.offerquestionnaire')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
