# Generated by Django 6.0.7 on 2026-07-18 20:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Enterprise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('website', models.URLField(blank=True, null=True)),
                ('sector', models.CharField(blank=True, max_length=100, null=True)),
                ('approximate_size', models.CharField(blank=True, max_length=50, null=True)),
                ('location', models.CharField(blank=True, max_length=200, null=True)),
                ('existing_crm_data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='VisitPreparation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hypothesis_to_verify', models.TextField(blank=True, default='')),
                ('custom_pitch', models.TextField(blank=True, default='')),
                ('key_questions', models.TextField(blank=True, default='')),
                ('meeting_objective', models.CharField(blank=True, default='', max_length=255)),
                ('scheduled_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('enterprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preparations', to='sales.enterprise')),
                ('salesperson', models.ForeignKey(limit_choices_to={'role': 'SALESPERSON'}, on_delete=django.db.models.deletion.CASCADE, related_name='preparations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='VisitReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_transcript', models.TextField(blank=True, default='')),
                ('executive_summary', models.TextField(blank=True, default='')),
                ('confirmed_needs', models.JSONField(blank=True, default=list)),
                ('objections_raised', models.JSONField(blank=True, default=list)),
                ('actions_todo', models.JSONField(blank=True, default=list)),
                ('follow_up_email_draft', models.TextField(blank=True, default='')),
                ('audio_file_path', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('preparation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='report', to='sales.visitpreparation')),
            ],
        ),
    ]
