# Generated by Django 5.2.14 on 2026-08-26 17:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_offerquestionnaire_offerquestion'),
        ('sales', '0009_clean_mock_plaques'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VisitFormSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_offer_name', models.CharField(help_text="Nom de l'offre ciblée (ex: Fibre Pro Orange 50M)", max_length=150)),
                ('answers', models.JSONField(default=list, help_text='Liste des réponses formatées [{question_id, question_text, answer}]')),
                ('ai_summary', models.TextField(blank=True, default='', help_text='Synthèse exécutive générée automatiquement pour le Back-Office')),
                ('qualification_score', models.PositiveIntegerField(default=75, help_text='Score de qualification de 0 à 100')),
                ('detected_needs', models.JSONField(blank=True, default=list, help_text='Besoins télécoms déduits des réponses')),
                ('objections_noted', models.TextField(blank=True, default='', help_text='Objections ou contraintes mentionnées')),
                ('next_action', models.CharField(default="Étude d'éligibilité technique & Contact KAM sous 24h", max_length=255)),
                ('status', models.CharField(choices=[('SUBMITTED', 'Soumis au Back-Office'), ('QUALIFIED', 'Qualifié (Transmis KAM)'), ('NEEDS_INFO', 'Informations Complémentaires Requises'), ('REJECTED', 'Non Éligible / Rejeté')], default='QUALIFIED', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('enterprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='form_submissions', to='sales.enterprise')),
                ('questionnaire', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submissions', to='catalog.offerquestionnaire')),
                ('salesperson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='form_submissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
