# Generated by Django 5.2.14 on 2026-09-04 16:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0010_visitformsubmission'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='enterprise',
            name='address',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='enterprise',
            name='annual_revenue',
            field=models.DecimalField(db_index=True, decimal_places=2, default=50000.0, help_text="Chiffre d'affaires annuel en USD (critère maître de segmentation)", max_digits=15),
        ),
        migrations.AddField(
            model_name='enterprise',
            name='assigned_entity',
            field=models.CharField(choices=[('BACK_OFFICE', 'Back-Office Terrain (Commerciaux Terrain & Plaques)'), ('KAM_OFFICE', 'Direction KAM & Grands Comptes (Desk KAM)')], db_index=True, default='BACK_OFFICE', max_length=30),
        ),
        migrations.AddField(
            model_name='enterprise',
            name='city',
            field=models.CharField(default='Kinshasa', max_length=100),
        ),
        migrations.AddField(
            model_name='enterprise',
            name='commune',
            field=models.CharField(blank=True, default='', help_text='Commune (ex: Gombe, Limete, Lingwala...)', max_length=100),
        ),
        migrations.AddField(
            model_name='enterprise',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='enterprise',
            name='contact_name',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='enterprise',
            name='contact_phone',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='enterprise',
            name='contact_role',
            field=models.CharField(blank=True, default='', help_text='Fonction du décideur (DG, DSI, Gérant...)', max_length=100),
        ),
        migrations.AddField(
            model_name='enterprise',
            name='conversion_notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='enterprise',
            name='conversion_status',
            field=models.CharField(choices=[('PROSPECT', 'Prospect non converti'), ('IN_NEGOTIATION', 'En cours de négociation'), ('CONVERTED', 'Converti / Signé'), ('LOST', 'Perdu / Non retenu')], db_index=True, default='PROSPECT', max_length=30),
        ),
        migrations.AddField(
            model_name='enterprise',
            name='converted_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Valeur contractuelle signée (USD)', max_digits=12),
        ),
        migrations.AddField(
            model_name='enterprise',
            name='converted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='enterprise',
            name='converted_by_entity',
            field=models.CharField(blank=True, choices=[('BACK_OFFICE', 'Back-Office Terrain'), ('KAM_OFFICE', 'KAM Office')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='enterprise',
            name='converted_by_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='converted_enterprises', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='enterprise',
            name='converted_offer',
            field=models.CharField(blank=True, default='', help_text='Offre commerciale souscrite', max_length=150),
        ),
        migrations.AddField(
            model_name='enterprise',
            name='crm_id',
            field=models.CharField(blank=True, db_index=True, help_text='Identifiant unique CRM (ex: CRM-CD-0001)', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='enterprise',
            name='current_connectivity',
            field=models.CharField(blank=True, default='4G LTE', help_text="Type d'accès actuel (Fibre, VSAT, 4G, Aucun)", max_length=100),
        ),
        migrations.AddField(
            model_name='enterprise',
            name='current_operator',
            field=models.CharField(blank=True, default='Vodacom', help_text='Opérateur actuel (Vodacom, Airtel, Africell, Canalbox...)', max_length=100),
        ),
        migrations.AddField(
            model_name='enterprise',
            name='employee_count',
            field=models.IntegerField(default=10, help_text='Effectif salarial'),
        ),
        migrations.AddField(
            model_name='enterprise',
            name='id_nat',
            field=models.CharField(blank=True, help_text="Numéro d'Identification Nationale", max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='enterprise',
            name='nif',
            field=models.CharField(blank=True, help_text="Numéro d'Impôt Fiscal", max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='enterprise',
            name='rccm',
            field=models.CharField(blank=True, help_text='Registre du Commerce et du Crédit Mobilier (ex: CD/KNG/RCCM/...)', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='enterprise',
            name='segment',
            field=models.CharField(choices=[('GRAND_COMPTE', 'Grand Compte'), ('PME', 'PME'), ('TPE_INFORMEL', 'TPE / Informel')], db_index=True, default='TPE_INFORMEL', max_length=30),
        ),
        migrations.AddField(
            model_name='enterprise',
            name='site_count',
            field=models.IntegerField(default=1, help_text="Nombre d'implantations / agences"),
        ),
        migrations.CreateModel(
            name='SegmentationConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tpe_max_revenue', models.DecimalField(decimal_places=2, default=100000.0, help_text='Seuil CA max pour TPE / Informel (USD). Les entreprises en dessous vont au Back-Office Terrain.', max_digits=15)),
                ('pme_max_revenue', models.DecimalField(decimal_places=2, default=1000000.0, help_text='Seuil CA max pour PME (USD). Les entreprises au dessus sont des Grands Comptes (KAM Office).', max_digits=15)),
                ('backoffice_entity_label', models.CharField(default='Back-Office Terrain', help_text="Nom de l'entité dédiée aux commerciaux de terrain et plaques", max_length=100)),
                ('kam_entity_label', models.CharField(default='Direction KAM & Grands Comptes', help_text="Nom de l'entité dédiée aux Key Account Managers et comptes stratégiques", max_length=100)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
