# Generated by Django 5.2.14 on 2026-09-05 09:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0012_enterprise_assigned_at_enterprise_assigned_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminDirective',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_entity', models.CharField(choices=[('KAM_OFFICE', 'Direction KAM Office'), ('BACK_OFFICE', 'Back-Office Terrain')], default='KAM_OFFICE', max_length=20)),
                ('title', models.CharField(help_text='Objet de la directive', max_length=200)),
                ('instruction', models.TextField(help_text='Contenu des instructions à appliquer')),
                ('priority', models.CharField(choices=[('NORMAL', 'Normale'), ('HIGH', 'Urgente'), ('CRITICAL', 'Stratégique')], default='NORMAL', max_length=20)),
                ('status', models.CharField(choices=[('SENT', 'Transmise'), ('IN_PROGRESS', "En cours d'application"), ('COMPLETED', 'Traitée / Conforme')], default='SENT', max_length=20)),
                ('target_account_name', models.CharField(blank=True, default='', help_text='Compte client concerné éventuel', max_length=200)),
                ('acknowledgement_note', models.TextField(blank=True, default='', help_text="Retour d'exécution du destinataire")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('recipient', models.ForeignKey(help_text='KAM ou Commercial/Superviseur ciblé', on_delete=django.db.models.deletion.CASCADE, related_name='received_directives', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_directives', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
