# Generated by Django 5.2.14 on 2026-09-06 15:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0013_admindirective'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='enterprise',
            name='assigned_salesperson',
            field=models.ForeignKey(blank=True, help_text='Commercial terrain individuel assigné pour la prospection', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_soho_enterprises', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='enterprise',
            name='assigned_salesperson_at',
            field=models.DateTimeField(blank=True, help_text="Date d'affectation au commercial", null=True),
        ),
        migrations.AddField(
            model_name='enterprise',
            name='is_visited',
            field=models.BooleanField(db_index=True, default=False, help_text="Vrai si l'entreprise a déjà été prospectée/visitée"),
        ),
        migrations.AddField(
            model_name='enterprise',
            name='last_visited_at',
            field=models.DateTimeField(blank=True, help_text='Date de la dernière visite terrain', null=True),
        ),
        migrations.AddField(
            model_name='enterprise',
            name='last_visited_by',
            field=models.ForeignKey(blank=True, help_text='Dernier commercial ayant visité cette entreprise', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visited_enterprises', to=settings.AUTH_USER_MODEL),
        ),
    ]
