# Generated by Django 6.0.7 on 2026-07-18 20:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('discovery', '0001_initial'),
        ('sales', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProspectDossier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('INBOUND_CONVERSATION', 'Conversation en ligne'), ('OUTBOUND_VISIT', 'Visite commerciale terrain')], default='INBOUND_CONVERSATION', max_length=30)),
                ('status', models.CharField(choices=[('NEW', 'Nouveau'), ('IN_REVIEW', 'En revue'), ('ACCEPTED', 'Accepté'), ('REJECTED', 'Rejeté')], default='NEW', max_length=20)),
                ('raw_qualification_data', models.JSONField(blank=True, default=dict, help_text='Consolidation des données de qualification (besoins, contraintes, outils actuels)')),
                ('internal_kam_notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('conversation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dossiers', to='discovery.clientconversation')),
                ('kam', models.ForeignKey(blank=True, limit_choices_to={'role': 'KAM'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_dossiers', to=settings.AUTH_USER_MODEL)),
                ('visit_report', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dossiers', to='sales.visitreport')),
            ],
        ),
    ]
