# Generated by Django 6.0.7 on 2026-07-26 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kam', '0002_prospectdossier_billing_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prospectdossier',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Brouillon'), ('QUALIFYING', 'Qualification en cours'), ('NEW', 'Nouveau / Qualifié'), ('DISPATCHED', 'Affecté au KAM'), ('IN_REVIEW', 'En revue'), ('ESTIMATE_PREPARED', 'Proposition commerciale rédigée'), ('NEGOTIATION', 'En négociation'), ('ACCEPTED', 'Signé / Accepté'), ('PROVISIONING', 'Provisioning technique'), ('COMPLETED', 'Installé / Opérationnel'), ('TRAINING', "En cours d'adoption / Formation"), ('REJECTED', 'Rejeté / Perdu')], default='NEW', max_length=20),
        ),
    ]
