# Generated by Django 5.2.14 on 2026-08-16 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kam', '0003_alter_prospectdossier_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prospectdossier',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
