# Generated by Django 5.2.14 on 2026-09-07 16:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kam', '0007_alter_prospectdossier_id'),
        ('sales', '0014_enterprise_assigned_salesperson_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KamAppointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('meeting_type', models.CharField(choices=[('PHYSICAL', 'Visite Terrain (Physique)'), ('GOOGLE_MEET', 'Google Meet / Visioconférence'), ('CALL', 'Appel Téléphonique')], default='PHYSICAL', max_length=20)),
                ('scheduled_at', models.DateTimeField()),
                ('duration_minutes', models.IntegerField(default=45)),
                ('location', models.CharField(blank=True, default='', max_length=255)),
                ('meet_url', models.URLField(blank=True, default='')),
                ('contact_name', models.CharField(blank=True, default='', max_length=150)),
                ('contact_role', models.CharField(blank=True, default='', max_length=100)),
                ('objective', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('SCHEDULED', 'Planifié'), ('IN_PROGRESS', 'En cours'), ('COMPLETED', 'Effectué / Rapport généré'), ('CANCELLED', 'Annulé')], default='SCHEDULED', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('enterprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kam_appointments', to='sales.enterprise')),
                ('kam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kam_appointments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['scheduled_at'],
            },
        ),
        migrations.CreateModel(
            name='KamVisitReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_transcript', models.TextField(blank=True, default='')),
                ('audio_file_path', models.CharField(blank=True, default='', max_length=255)),
                ('executive_summary', models.TextField(blank=True, default='')),
                ('confirmed_needs', models.JSONField(blank=True, default=list)),
                ('objections_raised', models.JSONField(blank=True, default=list)),
                ('actions_todo', models.JSONField(blank=True, default=list)),
                ('follow_up_email_draft', models.TextField(blank=True, default='')),
                ('bant_scores', models.JSONField(blank=True, default=dict)),
                ('conversion_status', models.CharField(default='IN_NEGOTIATION', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('appointment', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='report', to='kam.kamappointment')),
                ('enterprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kam_visit_reports', to='sales.enterprise')),
                ('kam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kam_visit_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
