# Generated by Django 5.2.14 on 2026-09-08 16:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kam', '0008_kamappointment_kamvisitreport'),
        ('sales', '0014_enterprise_assigned_salesperson_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='kamvisitreport',
            name='crm_payload',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='kamvisitreport',
            name='crm_sync_status',
            field=models.CharField(choices=[('PENDING', 'En attente'), ('SYNCED_DYNAMICS', 'Synchronisé Dynamics 365'), ('FAILED', 'Erreur de synchronisation')], default='PENDING', max_length=30),
        ),
        migrations.AddField(
            model_name='kamvisitreport',
            name='synced_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='PreCallBriefing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_overview', models.JSONField(blank=True, default=dict)),
                ('key_decision_makers', models.JSONField(blank=True, default=list)),
                ('detected_business_challenges', models.JSONField(blank=True, default=list)),
                ('custom_pitch_angles', models.JSONField(blank=True, default=list)),
                ('critical_discovery_questions', models.JSONField(blank=True, default=list)),
                ('golden_rules', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('enterprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pre_call_briefings', to='sales.enterprise')),
                ('kam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pre_call_briefings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
    ]
