# Generated by Django 6.0.7 on 2026-07-20 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_managers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('CLIENT_B2B', 'Client B2B'), ('SALESPERSON', 'Prospecteur / Commercial'), ('KAM', 'Key Account Manager'), ('COORDINATOR', 'Coordinateur / Dispatcher'), ('ADMIN', 'Administrateur MSP')], default='CLIENT_B2B', max_length=20),
        ),
    ]
