# Generated by Django 5.2.14 on 2026-09-04 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_user_fcm_token_userdevice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('CLIENT_B2B', 'Client B2B'), ('SALESPERSON', 'Commercial Terrain'), ('KAM', 'Key Account Manager'), ('SUPERVISOR', 'Superviseur Back-Office Terrain'), ('KAM_MANAGER', 'Gérant KAM Office / Grands Comptes'), ('ADMIN', 'Administrateur Onbora MSP')], default='CLIENT_B2B', max_length=20),
        ),
    ]
