# Generated by Django 5.2.14 on 2026-09-05 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_user_kam_specialization'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.CharField(blank=True, default='memoji_056.png', help_text='Nom du fichier memoji choisi', max_length=255),
        ),
    ]
