# Generated by Django 5.2.14 on 2026-09-16 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_aiassistantconversation_aiassistantmessage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_picture_url',
            field=models.URLField(blank=True, default='', help_text='URL de la photo de profil utilisateur', max_length=500),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.CharField(blank=True, default='', help_text='Nom du fichier avatar ou fallback', max_length=255),
        ),
    ]
