# Generated by Django 6.0.7 on 2026-07-18 20:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('kam', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessTwin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_state', models.JSONField(blank=True, default=list, help_text='Liste des problèmes identifiés et outils actuels (état initial)')),
                ('proposed_state', models.JSONField(blank=True, default=list, help_text='Liste des solutions apportées et bénéfices attendus (état cible)')),
                ('recommended_services', models.JSONField(blank=True, default=list, help_text='Détail des services recommandés du catalogue MSP avec justifications')),
                ('roadmap', models.JSONField(blank=True, default=list, help_text="Liste ordonnée d'étapes de déploiement simulé")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('prospect_dossier', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='business_twin', to='kam.prospectdossier')),
            ],
        ),
    ]
