# Generated by Django 6.0.7 on 2026-07-18 23:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DemoEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('CONVERSATION_STARTED', 'Début de qualification inbound'), ('MESSAGE_SENT', 'Message envoyé'), ('QUALIFICATION_SUCCESS', 'Qualification réussie'), ('DOSSIER_TRANSMITTED', 'Dossier transmis au KAM'), ('REPORT_GENERATED', 'Rapport commercial généré'), ('INTERNAL_NOTES_UPDATED', 'Notes internes KAM modifiées'), ('PDF_EXPORTED', 'PDF exporté')], max_length=50)),
                ('description', models.TextField()),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demo_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
