# Generated by Django 6.0.7 on 2026-07-26 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0002_alter_demoevent_event_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demoevent',
            name='event_type',
            field=models.CharField(choices=[('CONVERSATION_STARTED', 'Début de qualification inbound'), ('MESSAGE_SENT', 'Message envoyé'), ('QUALIFICATION_SUCCESS', 'Qualification réussie'), ('DOSSIER_TRANSMITTED', 'Dossier transmis au KAM'), ('REPORT_GENERATED', 'Rapport commercial généré'), ('INTERNAL_NOTES_UPDATED', 'Notes internes KAM modifiées'), ('PDF_EXPORTED', 'PDF exporté'), ('DOSSIER_DISPATCHED', 'Dossier affecté au KAM'), ('CRM_SYNCHRONIZED', 'Données synchronisées au CRM'), ('DOSSIER_IN_REVIEW', 'Dossier en revue par le KAM'), ('CLIENT_CONTACTED', 'Client contacté par le KAM'), ('MEETING_SCHEDULED', 'Rendez-vous planifié'), ('NEGOTIATION_STARTED', 'Négociation commencée'), ('APPROVAL_REQUESTED', 'Validation demandée'), ('DOSSIER_APPROVED', 'Dossier validé'), ('ORDER_PLACED', 'Commande passée sur le SI'), ('PROVISIONING_STARTED', 'Provisioning réseau démarré'), ('PROVISIONING_COMPLETED', 'Provisioning réseau complété'), ('ACTIVATION_STARTED', 'Activation démarrée'), ('DOSSIER_ACTIVE', 'Ligne active / Livrée'), ('DOSSIER_REJECTED', 'Dossier rejeté / Perdu')], max_length=50),
        ),
    ]
