# Generated by Django 5.2.14 on 2026-08-16 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0004_alter_demoevent_event_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demoevent',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
