# Generated by Django 5.2.14 on 2026-09-11 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_core', '0002_recommendation_snapshot_uniqueness'),
    ]

    operations = [
        migrations.CreateModel(
            name='AISessionMemory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(db_index=True, max_length=120, unique=True)),
                ('client_name', models.CharField(default='Compte B2B', max_length=255)),
                ('summary', models.TextField(blank=True, default='')),
                ('messages', models.JSONField(blank=True, default=list)),
                ('reports', models.JSONField(blank=True, default=list)),
                ('decision_status', models.CharField(choices=[('pending', 'En attente'), ('approved', 'Validé'), ('rejected', 'Rejeté')], default='pending', max_length=20)),
                ('validation_comment', models.TextField(blank=True, default='')),
                ('human_validation_required', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Session Mémoire IA',
                'verbose_name_plural': 'Sessions Mémoires IA',
                'ordering': ['-updated_at'],
            },
        ),
    ]
