# Generated by Django 6.0.7 on 2026-07-26 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScraperCredential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('LINKEDIN', 'LinkedIn'), ('TWITTER', 'Twitter / X'), ('TIKTOK', 'TikTok'), ('FACEBOOK', 'Facebook')], max_length=50, unique=True)),
                ('cookies_value', models.TextField(help_text='Chaîne brute des cookies ou valeur au format JSON.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
