# Generated by Django 6.0.7 on 2026-08-04 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_scrapercredential'),
    ]

    operations = [
        migrations.AddField(
            model_name='enterprise',
            name='arrowsphere_tenant_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='enterprise',
            name='kaabu_organization_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='enterprise',
            name='last_sync_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='enterprise',
            name='siren',
            field=models.CharField(blank=True, max_length=9, null=True, unique=True, verbose_name='Numéro SIREN'),
        ),
        migrations.AddField(
            model_name='enterprise',
            name='siret',
            field=models.CharField(blank=True, max_length=14, null=True, unique=True, verbose_name='Numéro SIRET'),
        ),
        migrations.AddField(
            model_name='enterprise',
            name='sync_status',
            field=models.CharField(choices=[('PENDING', 'En attente'), ('SYNCED', 'Synchronisé'), ('ERROR', 'Erreur de synchro')], default='PENDING', max_length=20),
        ),
    ]
