# Generated by Django 5.2.14 on 2026-08-19 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_alter_enterprise_id_alter_scrapercredential_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='enterprise',
            name='conversion_score',
            field=models.IntegerField(default=85),
        ),
        migrations.AddField(
            model_name='enterprise',
            name='is_ready_for_conversion',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='enterprise',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='enterprise',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='enterprise',
            name='plaque',
            field=models.CharField(db_index=True, default='Kinshasa (Gombe)', max_length=100),
        ),
        migrations.AddField(
            model_name='enterprise',
            name='recommended_solution',
            field=models.CharField(blank=True, default='Fibre Optique Pro + Microsoft 365', max_length=200),
        ),
        migrations.AlterField(
            model_name='enterprise',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='scrapercredential',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='visitpreparation',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='visitreport',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
