# Generated by Django 5.2.14 on 2026-08-20 16:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0005_enterprise_conversion_score_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='enterprise',
            name='ai_hypotheses',
            field=models.JSONField(blank=True, default=list, help_text='Hypothèses commerciales pré-visite'),
        ),
        migrations.AddField(
            model_name='enterprise',
            name='ai_key_questions',
            field=models.JSONField(blank=True, default=list, help_text='Questions stratégiques préconisées'),
        ),
        migrations.AddField(
            model_name='enterprise',
            name='ai_potential_objections',
            field=models.JSONField(blank=True, default=list, help_text='Objections probables et contre-arguments'),
        ),
        migrations.AddField(
            model_name='enterprise',
            name='ai_tailored_pitch',
            field=models.TextField(blank=True, default='', help_text="Pitch personnalisé généré par l'IA"),
        ),
        migrations.AddField(
            model_name='enterprise',
            name='scraped_data',
            field=models.JSONField(blank=True, default=dict, help_text='Données brutes issues du web et réseaux sociaux'),
        ),
        migrations.AddField(
            model_name='enterprise',
            name='scraping_status',
            field=models.CharField(choices=[('PENDING', 'En attente'), ('SCRAPED', 'Scrapé'), ('FAILED', 'Échoué')], default='PENDING', max_length=20),
        ),
        migrations.AddField(
            model_name='visitreport',
            name='ai_feedback_comments',
            field=models.TextField(blank=True, default='', help_text="Remarques et corrections apportées par l'humain"),
        ),
        migrations.AddField(
            model_name='visitreport',
            name='ai_feedback_rating',
            field=models.IntegerField(blank=True, help_text='Note attribuée par le commercial (1 à 5 étoiles)', null=True),
        ),
        migrations.AddField(
            model_name='visitreport',
            name='ai_feedback_sent_at',
            field=models.DateTimeField(blank=True, help_text="Date d'envoi du feedback au Core AI", null=True),
        ),
        migrations.AddField(
            model_name='visitreport',
            name='original_ai_output',
            field=models.JSONField(blank=True, default=dict, help_text='Sortie brute originale fournie par Core AI'),
        ),
        migrations.CreateModel(
            name='LiveVisitSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_status', models.CharField(choices=[('ACTIVE', 'Active'), ('PAUSED', 'En pause'), ('COMPLETED', 'Terminée')], default='ACTIVE', max_length=20)),
                ('live_transcript', models.TextField(blank=True, default='', help_text="Transcription incrémentale de l'échange")),
                ('detected_needs', models.JSONField(blank=True, default=list, help_text='Besoins détectés en temps réel')),
                ('detected_objections', models.JSONField(blank=True, default=list, help_text='Objections formulées en direct')),
                ('live_proposition', models.JSONField(blank=True, default=dict, help_text='JSON dynamique de proposition commerciale')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('enterprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='live_sessions', to='sales.enterprise')),
                ('preparation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='live_sessions', to='sales.visitpreparation')),
                ('salesperson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='live_sessions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Plaque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, help_text='Code unique de la plaque (ex: KIN-GOMBE)', max_length=50, unique=True)),
                ('name', models.CharField(help_text='Nom complet (ex: Kinshasa - Gombe)', max_length=150)),
                ('city', models.CharField(default='Kinshasa', max_length=100)),
                ('latitude', models.FloatField(default=-4.3033)),
                ('longitude', models.FloatField(default=15.3083)),
                ('radius_km', models.FloatField(default=5.0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_salespersons', models.ManyToManyField(blank=True, limit_choices_to={'role': 'SALESPERSON'}, related_name='assigned_plaques', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='enterprise',
            name='plaque_rel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enterprises', to='sales.plaque'),
        ),
    ]
