# Generated by Django 5.2.14 on 2026-08-22 21:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0006_enterprise_ai_hypotheses_enterprise_ai_key_questions_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FieldIntelligenceReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conversion_status', models.CharField(choices=[('SUCCESS', 'Pré-conversion réussie (Documents KYC / RCCM collectés)'), ('HESITATION', 'En réflexion / Hésitation'), ('REFUSAL', 'Refus / Non-converti')], default='SUCCESS', max_length=20)),
                ('rccm_number', models.CharField(blank=True, help_text='Numéro RCCM si succès', max_length=100, null=True)),
                ('nurturing_reason', models.CharField(choices=[('NONE', 'Aucun (Converti)'), ('DECIDER_ABSENT', 'Absence du décideur / gérant'), ('COMPETITOR_CONTRACT', 'Contrat concurrent en cours'), ('BUDGET_WAITING', "Attente d'arbitrage budgétaire"), ('COMMITMENT_FEAR', "Crainte d'engagement long terme"), ('TECHNICAL_DOUBT', "Doutes sur l'éligibilité technique / fibre"), ('OTHER', 'Autre motif')], default='NONE', max_length=30)),
                ('contract_expiry_date', models.DateField(blank=True, help_text="Date d'échéance du contrat concurrent actuel", null=True)),
                ('scheduled_follow_up', models.DateField(blank=True, help_text='Date de relance recommandée', null=True)),
                ('nurturing_notes', models.TextField(blank=True, default='', help_text='Notes contextuelles pour le rappel futur')),
                ('points_earned', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('enterprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='field_intelligence_reports', to='sales.enterprise')),
                ('salesperson', models.ForeignKey(limit_choices_to={'role': 'SALESPERSON'}, on_delete=django.db.models.deletion.CASCADE, related_name='field_intelligence_reports', to=settings.AUTH_USER_MODEL)),
                ('visit_report', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='field_intelligence', to='sales.visitreport')),
            ],
        ),
        migrations.CreateModel(
            name='NearbyLead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Nom de l'enseigne ou commerce voisin", max_length=150)),
                ('sector', models.CharField(blank=True, default='Commerce / PME', max_length=100)),
                ('manager_name', models.CharField(blank=True, default='', max_length=100)),
                ('phone', models.CharField(blank=True, default='', max_length=50)),
                ('proximity_notes', models.CharField(blank=True, default='', help_text='Ex: 2 portes à gauche, en face...', max_length=255)),
                ('photo_url', models.TextField(blank=True, default='', help_text='Photo de la devanture (URL ou Data URI)')),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('status', models.CharField(choices=[('NEW', 'Nouveau repérage'), ('ASSIGNED', 'Affecté à un commercial'), ('VISITED', 'Visité'), ('CONVERTED', 'Converti')], default='NEW', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('field_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nearby_leads', to='sales.fieldintelligencereport')),
                ('source_enterprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nearby_lookalikes', to='sales.enterprise')),
            ],
        ),
        migrations.CreateModel(
            name='ReferralLead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referral_type', models.CharField(choices=[('SUPPLIER', 'Fournisseur principal'), ('PARTNER', 'Partenaire commercial'), ('PEER', 'Confrère / Recommandation directe')], default='SUPPLIER', max_length=20)),
                ('company_name', models.CharField(max_length=150)),
                ('contact_person', models.CharField(blank=True, default='', max_length=100)),
                ('phone', models.CharField(blank=True, default='', max_length=50)),
                ('notes', models.TextField(blank=True, default='', help_text='Pourquoi cette entreprise a besoin de nos solutions ?')),
                ('status', models.CharField(choices=[('NEW', 'Nouveau parrainage'), ('CONTACTED', 'Contacté'), ('CONVERTED', 'Converti')], default='NEW', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('field_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referrals', to='sales.fieldintelligencereport')),
                ('source_enterprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generated_referrals', to='sales.enterprise')),
            ],
        ),
        migrations.CreateModel(
            name='SalesIncentivePoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('PRE_CONVERSION', 'Pré-conversion réussie (KYC/RCCM) [+100 pts]'), ('NEARBY_LEAD', 'Lead voisin 100m qualifié (photo + contact) [+25 pts]'), ('REFERRAL', 'Parrainage / Fournisseur renseigné [+15 pts]'), ('TRADE_AUDIT', 'Audit concurrentiel renseigné [+10 pts]')], max_length=30)),
                ('points', models.IntegerField(default=10)),
                ('description', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('field_report', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incentive_points', to='sales.fieldintelligencereport')),
                ('salesperson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incentive_points', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TradeAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('competitor_name', models.CharField(help_text='Opérateur ou FAI actuel (ex: Canalbox, Vodacom, Airtel, etc.)', max_length=100)),
                ('satisfaction_score', models.IntegerField(default=3, help_text='Note de 1 (Très insatisfait) à 5 (Très satisfait)')),
                ('friction_reasons', models.JSONField(blank=True, default=list, help_text='Motifs de mécontentement (pannes, lenteurs, prix...)')),
                ('monthly_spend_estimated', models.DecimalField(blank=True, decimal_places=2, help_text='Facture mensuelle estimée', max_digits=10, null=True)),
                ('is_priority_friction_alert', models.BooleanField(default=False)),
                ('alert_notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('enterprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trade_audits', to='sales.enterprise')),
                ('field_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trade_audits', to='sales.fieldintelligencereport')),
            ],
        ),
    ]
