# Generated by Django 5.2.14 on 2026-08-23 20:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0007_fieldintelligencereport_nearbylead_referrallead_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='plaque',
            name='boundary_geojson',
            field=models.JSONField(blank=True, default=dict, help_text='GeoJSON Polygon / MultiPolygon de la zone délimitée'),
        ),
        migrations.AddField(
            model_name='plaque',
            name='kml_data',
            field=models.TextField(blank=True, default='', help_text='Fichier KML standard décrivant le tracé géographique'),
        ),
        migrations.AlterField(
            model_name='salesincentivepoint',
            name='action_type',
            field=models.CharField(choices=[('PRE_CONVERSION', 'Pré-conversion réussie (KYC/RCCM) [+5 pts]'), ('NEARBY_LEAD', 'Lead voisin 100m qualifié (photo + contact) [+1 pt]'), ('REFERRAL', 'Parrainage / Fournisseur renseigné [+1 pt]'), ('TRADE_AUDIT', 'Audit concurrentiel renseigné [+1 pt]')], max_length=30),
        ),
        migrations.AlterField(
            model_name='salesincentivepoint',
            name='points',
            field=models.IntegerField(default=1),
        ),
        migrations.CreateModel(
            name='SalesNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('notification_type', models.CharField(choices=[('PLAQUE_ASSIGNED', 'Plaque Assignée'), ('TERRITORY_UPDATE', 'Mise à jour Territoire & KML'), ('NEW_LEAD', 'Nouveau Prospect Détecté'), ('ALERT', 'Alerte Système')], default='PLAQUE_ASSIGNED', max_length=50)),
                ('payload', models.JSONField(blank=True, default=dict, help_text='Données supplémentaires (kml_url, coordonnées, ids)')),
                ('is_read', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('plaque', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='sales.plaque')),
                ('recipient', models.ForeignKey(limit_choices_to={'role': 'SALESPERSON'}, on_delete=django.db.models.deletion.CASCADE, related_name='sales_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
