# Generated by Django 5.2.14 on 2026-09-04 17:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0011_enterprise_address_enterprise_annual_revenue_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='enterprise',
            name='assigned_at',
            field=models.DateTimeField(blank=True, help_text="Date d'affectation par le KAM Office", null=True),
        ),
        migrations.AddField(
            model_name='enterprise',
            name='assigned_by',
            field=models.ForeignKey(blank=True, help_text="Gérant KAM Office ayant opéré l'affectation", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dispatched_enterprises', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='enterprise',
            name='assigned_kam',
            field=models.ForeignKey(blank=True, help_text='Key Account Manager (KAM) individuel affecté à ce compte par le KAM Office', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_kam_enterprises', to=settings.AUTH_USER_MODEL),
        ),
    ]
