# Generated by Django 5.2.14 on 2026-09-10 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0014_enterprise_assigned_salesperson_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='enterprise',
            options={'ordering': ['-created_at'], 'verbose_name': 'Compte Entreprise (CRM B2B)', 'verbose_name_plural': 'Répertoire CRM des Entreprises B2B'},
        ),
        migrations.AddField(
            model_name='enterprise',
            name='ai_churn_data',
            field=models.JSONField(blank=True, default=dict, help_text='Dernier diagnostic Churn Radar & Upsell (Core AI)'),
        ),
        migrations.AddField(
            model_name='enterprise',
            name='ai_lead_scoring_data',
            field=models.JSONField(blank=True, default=dict, help_text="Dernière évaluation d'intelligence commerciale Lead Scoring (Core AI)"),
        ),
        migrations.AddField(
            model_name='enterprise',
            name='ai_scored_at',
            field=models.DateTimeField(blank=True, help_text="Date et heure du dernier calcul d'inférence Core AI", null=True),
        ),
        migrations.AddField(
            model_name='enterprise',
            name='budget_status',
            field=models.CharField(blank=True, default='Non précisé', help_text='Statut budgétaire IT / Télécoms (Validé, En arbitrage, Bloqué...)', max_length=150),
        ),
        migrations.AddField(
            model_name='enterprise',
            name='contract_end_date',
            field=models.DateField(blank=True, db_index=True, help_text="Date d'échéance du contrat opérateur concurrent / actuel", null=True),
        ),
        migrations.AddField(
            model_name='enterprise',
            name='incident_count',
            field=models.IntegerField(default=0, help_text="Nombre d'incidents / pannes réseau non résolus sur les 90 derniers jours"),
        ),
        migrations.AddField(
            model_name='enterprise',
            name='pain_level',
            field=models.CharField(blank=True, choices=[('Faible', 'Faible'), ('Modéré', 'Modéré'), ('Critique', 'Critique')], default='Modéré', help_text='Niveau de frustration ou de criticité ressenti vis-à-vis du fournisseur actuel', max_length=50),
        ),
        migrations.AddField(
            model_name='enterprise',
            name='telecom_budget_monthly',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Budget télécoms mensuel estimé ou réel en USD', max_digits=12, null=True),
        ),
        migrations.AlterModelTable(
            name='enterprise',
            table='sales_enterprise',
        ),
    ]
