# Generated by Django 5.2.14 on 2026-09-16 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0015_alter_enterprise_options_enterprise_ai_churn_data_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enterprise',
            name='current_operator',
        ),
        migrations.DeleteModel(
            name='AdminDirective',
        ),
    ]
