# Generated by Django 5.2.14 on 2026-09-16 11:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0016_remove_enterprise_current_operator_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScoreProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nom affiché dans Onbora (ex: Santé relationnelle client)', max_length=150)),
                ('score_type', models.CharField(choices=[('ACCOUNT_HEALTH', 'Santé & Risque de désengagement'), ('EXPANSION_UPSELL', 'Potentiel d’Expansion & Upsell')], default='ACCOUNT_HEALTH', max_length=30)),
                ('objective', models.CharField(blank=True, help_text='Ce que le score sert à détecter', max_length=255)),
                ('population', models.CharField(default='Tous les clients actifs', help_text='Quels comptes sont calculés', max_length=100)),
                ('analysis_window_days', models.PositiveIntegerField(default=90, help_text='Fenêtre de temps à observer (ex: 90 jours)')),
                ('recalculation_frequency', models.CharField(default='Chaque nuit', help_text='Fréquence de recalcul (ex: Chaque nuit)', max_length=30)),
                ('base_score', models.IntegerField(default=100, help_text='Score de base initial (100 pour santé, 0 pour upsell)')),
                ('dimensions', models.JSONField(default=list, help_text='Liste des dimensions actives et de leurs poids')),
                ('thresholds', models.JSONField(default=list, help_text='Seuils de résultat et libellés')),
                ('actions', models.JSONField(blank=True, default=dict, help_text="Actions déclenchées selon le niveau d'alerte")),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ScoreRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Libellé lisible de la condition', max_length=255)),
                ('dimension', models.CharField(help_text='engagement, relation, commercial, sentiment', max_length=50)),
                ('field', models.CharField(help_text='Nom du champ métrique (ex: days_since_last_meeting)', max_length=100)),
                ('operator', models.CharField(help_text='greater_than, less_than, is_true, equals, etc.', max_length=50)),
                ('value', models.JSONField(default=dict, help_text="Valeur seuil cible (ex: 60, true, 'devis')")),
                ('points', models.IntegerField(help_text='Points ajoutés (positif) ou retirés (négatif)')),
                ('valid_for_days', models.PositiveIntegerField(blank=True, help_text='Durée de validité du signal en jours', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='sales.scoreprofile')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='AccountScoreResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(help_text='Score final calculé entre 0 et 100')),
                ('status_label', models.CharField(help_text='Ex: Sain, À surveiller, Critique', max_length=50)),
                ('status_color', models.CharField(default='blue', max_length=20)),
                ('triggered_rules', models.JSONField(default=list, help_text='Liste transparente des règles déclenchées')),
                ('dimension_scores', models.JSONField(default=dict, help_text='Sous-totaux de points par dimension')),
                ('metrics_snapshot', models.JSONField(blank=True, default=dict, help_text='Instantané des métriques ayant servi au calcul')),
                ('calculated_at', models.DateTimeField(auto_now=True)),
                ('enterprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scoring_results', to='sales.enterprise')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_results', to='sales.scoreprofile')),
            ],
            options={
                'ordering': ['-score'],
                'unique_together': {('enterprise', 'profile')},
            },
        ),
    ]
