# Generated by Django 5.2.14 on 2026-09-21 15:47

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0017_scoreprofile_scorerule_accountscoreresult'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountProjection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('crm_account_id', models.CharField(db_index=True, help_text='Identifiant unique dans Microsoft Dynamics 365 / Dataverse', max_length=100, unique=True)),
                ('source_system', models.CharField(choices=[('DYNAMICS_365', 'Microsoft Dynamics 365 Sales'), ('KAABU', 'CRM Kaabu Orange'), ('LOCAL_ONLY', 'Compte créé localement / Non synchronisé')], default='DYNAMICS_365', max_length=50)),
                ('source_version', models.CharField(blank=True, default='', help_text='Numéro de version / ETag du système source pour contrôle de concurrence', max_length=100)),
                ('raw_crm_payload', models.JSONField(blank=True, default=dict, help_text='Dernier snapshot JSON reçu du CRM maître')),
                ('last_pulled_at', models.DateTimeField(blank=True, help_text='Date de dernière lecture incrémentale depuis le CRM', null=True)),
                ('last_pushed_at', models.DateTimeField(blank=True, help_text='Date de dernière écriture confirmée vers le CRM', null=True)),
                ('sync_status', models.CharField(choices=[('IN_SYNC', 'Synchronisé et à jour'), ('PENDING_PULL', 'Mise à jour distante disponible'), ('PENDING_PUSH', "Modifications locales en attente d'écriture"), ('CONFLICT', 'Conflit de version nécessitant arbitrage'), ('ERROR', 'Erreur lors de la dernière tentative')], default='IN_SYNC', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('enterprise', models.OneToOneField(help_text='Fiche entreprise Onbora rattachée à cette projection', on_delete=django.db.models.deletion.CASCADE, related_name='crm_projection', to='sales.enterprise')),
            ],
            options={
                'verbose_name': 'Projection CRM Compte',
                'verbose_name_plural': 'Projections CRM Comptes',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='SourceObservation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_type', models.CharField(choices=[('PUBLIC_REGISTRY', 'Registre du Commerce / Fisc (RCCM, IdNat)'), ('OFFICIAL_GAZETTE', 'Journal Officiel / Marchés Publics'), ('COMPANY_WEBSITE', "Site Web Officiel de l'Entreprise"), ('NEWS_MEDIA', 'Presse Économique / Média Spécialisé'), ('FIELD_VISIT', "Constat direct lors d'une visite terrain"), ('CRM_ACTIVITY', "Historique d'activité CRM validé")], db_index=True, max_length=30)),
                ('source_uri', models.CharField(help_text='URL de la source ou identifiant officiel', max_length=500)),
                ('source_title', models.CharField(blank=True, default='', help_text='Titre ou description courte de la source', max_length=255)),
                ('observed_at', models.DateTimeField(db_index=True, help_text="Date exacte de parution ou de constat de l'observation")),
                ('captured_at', models.DateTimeField(auto_now_add=True, help_text="Date d'enregistrement dans Onbora")),
                ('excerpt_text', models.TextField(help_text="Extrait textuel brut étayant l'observation")),
                ('excerpt_hash', models.CharField(blank=True, db_index=True, default='', help_text="Empreinte SHA256 de l'extrait pour déduplication", max_length=64)),
                ('status', models.CharField(choices=[('COLLECTED', 'Collectée (Brute)'), ('VERIFIED', 'Vérifiée par opérateur'), ('REJECTED', 'Rejetée (Non pertinente ou obsolète)')], default='COLLECTED', max_length=20)),
                ('captured_by', models.ForeignKey(blank=True, help_text="Utilisateur ayant capturé l'observation (si saisie manuelle)", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='captured_observations', to=settings.AUTH_USER_MODEL)),
                ('enterprise', models.ForeignKey(help_text='Entreprise concernée', on_delete=django.db.models.deletion.CASCADE, related_name='source_observations', to='sales.enterprise')),
            ],
            options={
                'verbose_name': 'Observation Sourcée',
                'verbose_name_plural': 'Observations Sourcées',
                'ordering': ['-observed_at'],
            },
        ),
        migrations.CreateModel(
            name='Evidence',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('FACT', 'Fait avéré et prouvé'), ('HYPOTHESIS', 'Hypothèse commerciale à confirmer'), ('UNKNOWN', 'Inconnue critique / Donnée manquante')], db_index=True, default='HYPOTHESIS', max_length=20)),
                ('category', models.CharField(default='BUSINESS', help_text='Ex: CONNECTIVITY, GOVERNANCE, BUDGET, SITES, HARDWARE, RISK', max_length=50)),
                ('statement', models.TextField(help_text="Énoncé clair de l'affirmation commerciale ou de l'inconnue")),
                ('confidence_score', models.DecimalField(decimal_places=2, default=0.7, help_text='Score de certitude (0.00 à 1.00)', max_digits=4)),
                ('review_status', models.CharField(choices=[('TO_CONFIRM', 'À confirmer en entretien'), ('CONFIRMED', 'Confirmé et validé'), ('REJECTED', 'Infirmé / Rejeté')], db_index=True, default='TO_CONFIRM', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('valid_from', models.DateTimeField(auto_now_add=True)),
                ('valid_until', models.DateTimeField(blank=True, help_text='Date de caducité du fait', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('enterprise', models.ForeignKey(help_text='Entreprise concernée', on_delete=django.db.models.deletion.CASCADE, related_name='evidences', to='sales.enterprise')),
                ('reviewed_by', models.ForeignKey(blank=True, help_text='Commercial ou KAM ayant confirmé le fait', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_evidences', to=settings.AUTH_USER_MODEL)),
                ('observation', models.ForeignKey(blank=True, help_text='Observation source justifiant cette preuve', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='derived_evidences', to='sales.sourceobservation')),
            ],
            options={
                'verbose_name': 'Preuve & Fait Qualifié',
                'verbose_name_plural': 'Preuves & Faits Qualifiés',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AccountPortfolioAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('assignment_type', models.CharField(choices=[('PRIMARY_KAM', 'KAM Titulaire (PME & Grands Comptes)'), ('BACKUP_KAM', 'KAM Suppléant (Binôme / Backup)'), ('SOHO_REPRESENTATIVE', 'Prospecteur / Prestataire Terrain (SOHO)'), ('TECHNICAL_SALES', 'Ingénieur Avant-Vente / Spécialiste')], db_index=True, default='PRIMARY_KAM', max_length=30)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('assigned_by', models.ForeignKey(blank=True, help_text="Manager ayant validé l'affectation", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dispatched_assignments', to=settings.AUTH_USER_MODEL)),
                ('enterprise', models.ForeignKey(help_text='Entreprise assignée', on_delete=django.db.models.deletion.CASCADE, related_name='portfolio_assignments', to='sales.enterprise')),
                ('user', models.ForeignKey(help_text='Utilisateur assigné (KAM ou Commercial SOHO)', on_delete=django.db.models.deletion.CASCADE, related_name='account_assignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Affectation Portefeuille',
                'verbose_name_plural': 'Affectations Portefeuilles',
                'ordering': ['-assigned_at'],
                'unique_together': {('enterprise', 'user', 'assignment_type')},
            },
        ),
    ]
