# Generated by Django 5.2.14 on 2026-09-21 16:12

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0018_accountprojection_sourceobservation_evidence_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IdempotencyRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('idempotency_key', models.CharField(db_index=True, max_length=128, unique=True)),
                ('operation_type', models.CharField(db_index=True, default='VISIT_COMPLETE', max_length=50)),
                ('request_hash', models.CharField(blank=True, default='', help_text='SHA256 du payload requête', max_length=64)),
                ('response_status', models.IntegerField(default=200)),
                ('response_payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='idempotent_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "Enregistrement d'Idempotence",
                'verbose_name_plural': "Enregistrements d'Idempotence",
                'ordering': ['-created_at'],
            },
        ),
    ]
